# Generated by Django 4.2.15 on 2024-12-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Driver Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Driver Phone')),
                ('id_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Driver Id Number')),
                ('language', models.CharField(blank=True, choices=[('ar', 'عربي'), ('en', 'انجليزية'), ('ur', 'اوردو')], max_length=120, null=True, verbose_name='Driver Language')),
                ('truck_type', models.CharField(blank=True, choices=[('تريلة سطحة', 'تريلة سطحة'), ('تريلة ستارة', 'تريلة ستارة'), ('تريلة جوانب', 'تريلة جوانب'), ('تريلة براد', 'تريلة براد'), ('لوري عايدي', 'لوري عايدي'), ('لوري براد', 'لوري براد'), ('دينه عايدي', 'دينه عايدي'), ('دينة براد', 'دينة براد')], max_length=120, null=True, verbose_name='Truck Type')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Rate')),
                ('image_id', models.ImageField(blank=True, default='driver_image/id_defult.png', null=True, upload_to='driver_image', verbose_name='Driver Image')),
            ],
        ),
    ]
