# Generated by Django 4.2.15 on 2024-12-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='City Arabic')),
                ('name_en', models.CharField(max_length=50, verbose_name='City English')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='Status English')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Status Arabic')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status Stages')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('premium', models.IntegerField(blank=True, null=True, verbose_name='Premium')),
                ('fare_return', models.IntegerField(blank=True, null=True, verbose_name='Return')),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
                ('days_stayed', models.IntegerField(blank=True, null=True, verbose_name='Days Stayed ')),
                ('stay_cost', models.IntegerField(blank=True, null=True, verbose_name='Stay Cost')),
                ('deducted', models.IntegerField(blank=True, null=True, verbose_name='Deducted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create At')),
                ('expected_arrival_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expected Arrival Date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Actual Delivery Date ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_company', to='customers.branch')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.city', verbose_name='Destination')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_driver', to='drivers.driver')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.shipmentstatus', verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
